flowchart LR
    F[fa:fa-shirt Product 1] --> A[&nbsp\n Batched \nRequest\n\n] ---> |call|C
    E[fa:fa-shirt Product 2]--> A
    D[fa:fa-shirt Product 3]--> A 

 C[&nbsp\n\n Discounts API\n\n\n]

 {
  "theme": "base",
  "themeVariables": {
    "primaryColor": "#fff",
    "primaryTextColor": "#041E2F",
    "tertiaryTextColor": "#fffff",
    "primaryBorderColor": "#FF330F",
    "lineColor": "#6A90D2",
    "secondaryColor": "#6A90D2",
    "tertiaryColor": "#F2F3F5",
    "clusterBorder": "#000"
  }
}