flowchart LR
    F[fa:fa-shirt Product 1] --->|call| C[&nbsp\n\n Discounts API\n\n\n]
    E[fa:fa-shirt Product 2] --->|call| C
    D[fa:fa-shirt Product 3] --->|call| C

{
  "theme": "base",
  "themeVariables": {
    "primaryColor": "#fff",
    "primaryTextColor": "#041E2F",
    "tertiaryTextColor": "#fffff",
    "primaryBorderColor": "#FF330F",
    "lineColor": "#6A90D2",
    "secondaryColor": "#fff",
    "tertiaryColor": "#F2F3F5",
    "clusterBorder": "#000"
  }
}